# Use official Node.js LTS image
FROM node:18-alpine

# Create app directory
WORKDIR /usr/src/app

# Install app dependencies
COPY package*.json ./
RUN npm install --production --legacy-peer-deps

# Bundle app source
COPY backend/src/ ./src/

# Expose port
EXPOSE 8000

# Start the backend server
CMD ["npm", "run", "dev"]
