version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "8001:8000"
    environment:
      - NODE_ENV=production
    volumes:
      - ./backend:/usr/src/app
    command: npm run dev

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "8000:8000"
    environment:
      - NODE_ENV=production
    volumes:
      - ./:/usr/src/app
    command: npm run dev
    depends_on:
      - backend
